#include "nastran_io.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <unordered_map>

namespace {

std::string trim(const std::string& s) {
  const auto begin = std::find_if_not(s.begin(), s.end(), [](unsigned char c) { return std::isspace(c) != 0; });
  if (begin == s.end()) {
    return {};
  }
  const auto end = std::find_if_not(s.rbegin(), s.rend(), [](unsigned char c) { return std::isspace(c) != 0; }).base();
  return std::string(begin, end);
}

std::vector<std::string> split_tokens(std::string line) {
  line = trim(line);
  if (line.empty()) {
    return {};
  }

  const auto comment_pos = line.find('$');
  if (comment_pos != std::string::npos) {
    line = line.substr(0, comment_pos);
  }
  line = trim(line);
  if (line.empty()) {
    return {};
  }

  for (char& c : line) {
    if (c == ',') {
      c = ' ';
    }
  }

  std::stringstream ss(line);
  std::vector<std::string> tokens;
  std::string token;
  while (ss >> token) {
    tokens.push_back(token);
  }
  return tokens;
}

int to_int(const std::string& s) {
  return std::stoi(s);
}

double to_double(const std::string& s) {
  return std::stod(s);
}

}  // namespace

SurfaceMesh read_nastran_surface(const std::string& path) {
  std::ifstream in(path);
  if (!in) {
    throw std::runtime_error("Failed to open input file: " + path);
  }

  std::unordered_map<int, int> id_to_index;
  SurfaceMesh mesh;

  std::string line;
  while (std::getline(in, line)) {
    auto tokens = split_tokens(line);
    if (tokens.empty()) {
      continue;
    }

    const std::string& card = tokens[0];
    if (card == "GRID" || card == "GRID*") {
      if (tokens.size() < 5) {
        throw std::runtime_error("GRID card has insufficient fields: " + line);
      }
      const int id = to_int(tokens[1]);
      const double x = to_double(tokens[tokens.size() - 3]);
      const double y = to_double(tokens[tokens.size() - 2]);
      const double z = to_double(tokens[tokens.size() - 1]);

      if (id_to_index.find(id) != id_to_index.end()) {
        throw std::runtime_error("Duplicate GRID id found: " + std::to_string(id));
      }

      id_to_index[id] = static_cast<int>(mesh.points.size());
      mesh.points.push_back({x, y, z});
    } else if (card == "CTRIA3") {
      if (tokens.size() < 6) {
        throw std::runtime_error("CTRIA3 card has insufficient fields: " + line);
      }
      TriFace tri{};
      tri.v[0] = to_int(tokens[tokens.size() - 3]);
      tri.v[1] = to_int(tokens[tokens.size() - 2]);
      tri.v[2] = to_int(tokens[tokens.size() - 1]);
      mesh.triangles.push_back(tri);
    } else if (card == "CQUAD4") {
      if (tokens.size() < 7) {
        throw std::runtime_error("CQUAD4 card has insufficient fields: " + line);
      }
      const int a = to_int(tokens[tokens.size() - 4]);
      const int b = to_int(tokens[tokens.size() - 3]);
      const int c = to_int(tokens[tokens.size() - 2]);
      const int d = to_int(tokens[tokens.size() - 1]);
      mesh.triangles.push_back({{a, b, c}});
      mesh.triangles.push_back({{a, c, d}});
    }
  }

  if (mesh.points.empty()) {
    throw std::runtime_error("No GRID nodes found. Please check the Nastran bdf/nas format.");
  }
  if (mesh.triangles.empty()) {
    throw std::runtime_error("No surface elements found (CTRIA3/CQUAD4).");
  }

  for (TriFace& tri : mesh.triangles) {
    for (int& node_id : tri.v) {
      auto it = id_to_index.find(node_id);
      if (it == id_to_index.end()) {
        throw std::runtime_error("Surface element references a missing GRID id: " + std::to_string(node_id));
      }
      node_id = it->second;
    }
  }

  return mesh;
}

void write_nastran_tets(const std::string& path, const TetMesh& mesh) {
  std::ofstream out(path);
  if (!out) {
    throw std::runtime_error("Failed to write output file: " + path);
  }

  out << "$ Generated by nas2tet\n";
  out << std::scientific << std::setprecision(9);

  for (size_t i = 0; i < mesh.points.size(); ++i) {
    const auto& p = mesh.points[i];
    out << "GRID," << (i + 1) << ",," << p.x << ',' << p.y << ',' << p.z << '\n';
  }

  for (size_t i = 0; i < mesh.tets.size(); ++i) {
    const auto& t = mesh.tets[i];
    out << "CTETRA," << (i + 1) << ",1," << (t.v[0] + 1) << ',' << (t.v[1] + 1) << ',' << (t.v[2] + 1)
        << ',' << (t.v[3] + 1) << '\n';
  }

  out << "ENDDATA\n";
}

void write_vtu(const std::string& path, const TetMesh& mesh) {
  std::ofstream out(path);
  if (!out) {
    throw std::runtime_error("Failed to write VTU file: " + path);
  }

  out << "<?xml version=\"1.0\"?>\n";
  out << "<VTKFile type=\"UnstructuredGrid\" version=\"0.1\" byte_order=\"LittleEndian\">\n";
  out << "  <UnstructuredGrid>\n";
  out << "    <Piece NumberOfPoints=\"" << mesh.points.size() << "\" NumberOfCells=\"" << mesh.tets.size() << "\">\n";
  out << "      <Points>\n";
  out << "        <DataArray type=\"Float64\" NumberOfComponents=\"3\" format=\"ascii\">\n";
  out << std::scientific << std::setprecision(9);
  for (const auto& p : mesh.points) {
    out << "          " << p.x << ' ' << p.y << ' ' << p.z << '\n';
  }
  out << "        </DataArray>\n";
  out << "      </Points>\n";

  out << "      <Cells>\n";
  out << "        <DataArray type=\"Int32\" Name=\"connectivity\" format=\"ascii\">\n";
  for (const auto& t : mesh.tets) {
    out << "          " << t.v[0] << ' ' << t.v[1] << ' ' << t.v[2] << ' ' << t.v[3] << '\n';
  }
  out << "        </DataArray>\n";

  out << "        <DataArray type=\"Int32\" Name=\"offsets\" format=\"ascii\">\n";
  int offset = 0;
  for (size_t i = 0; i < mesh.tets.size(); ++i) {
    offset += 4;
    out << "          " << offset << '\n';
  }
  out << "        </DataArray>\n";

  out << "        <DataArray type=\"UInt8\" Name=\"types\" format=\"ascii\">\n";
  for (size_t i = 0; i < mesh.tets.size(); ++i) {
    out << "          10\n";
  }
  out << "        </DataArray>\n";
  out << "      </Cells>\n";
  out << "    </Piece>\n";
  out << "  </UnstructuredGrid>\n";
  out << "</VTKFile>\n";
}
